### ISSUE TITLE
F-14 ya esta filtrando bien

### ISSUE THREAD

**Issue by BlancaInesAcosta** [pasosdeJesus/cor1440#14]
![Captura de pantalla de 2020-06-28 11-47-27](https://user-images.githubusercontent.com/10052756/86376924-5141ec80-bc4d-11ea-8a76-4fe87e2929bb.png)
F-14 Al filtrar proyectos en https://defensor.info/cor1440/ genera error

**Comment by vtamara** [comment]
Instrucciones para reproducir por favor.
