### ISSUE TITLE
F-30 Al intentar generar reporte de beneficiarios por actividad de marco lógico del primer semestre del año 2021  PROYECTO ANDINO DE LA IMCOL no realiza el conteo cuando existen mas de 5 beneficiarios para este proyecto.

### ISSUE THREAD

**Issue by pmartinez5** [pasosdeJesus/cor1440#30]
En esta imagen se evidencian los beneficiarios de la actividad con Id 973
[
![FireShot Capture 161 - Cor1440 1 0b5 - defensor info](https://user-images.githubusercontent.com/61369119/140249415-3bf9e229-1a7d-48a6-8a89-b019c1ba58bb.png)
](url)

**Comment by pmartinez5** [comment]
En esta imagen se evidencia que no realiza el conteo de beneficiarios.
[
![FireShot Capture 162 - Cor1440 1 0b5 - defensor info](https://user-images.githubusercontent.com/61369119/140249964-0f4e770b-e064-4fd0-8f1d-a48042036a0a.png)
](url)

**Comment by vtamara** [comment]
Tal vez no tenía actividades en ese periodo de tiempo. Lo veo operando.

**Comment by pmartinez5** [comment]
Gracias
